export const lugaresDeEspaña = [
  "Madrid",
  "Barcelona",
  "Valencia",
  "Sevilla",
  "Zaragoza",
  "Málaga",
  "Murcia",
  "Palma de Mallorca",
  "Las Palmas de Gran Canaria",
  "Bilbao",
  "Alicante",
  "Córdoba",
  "Granada",
  "Valladolid",
  "Vigo",
  "Gijón",
  "L'Hospitalet de Llobregat",
  "A Coruña",
  "Vitoria-Gasteiz",
  "Gran Canaria",
  "Santander",
  "San Sebastián",
  "Tarragona",
  "Pamplona",
  "Almería",
  "Castellón de la Plana",
  "Badajoz",
  "Salamanca",
  "Logroño",
  "Huelva",
  "Cádiz",
  "León",
  "Ciudad Real",
  "Lleida",
  "Jaén",
  "Ávila",
  "Toledo",
  "Segovia",
  "Cuenca",
  "Burgos",
  "Santiago de Compostela",
  "Lugo",
  "Ourense",
  "Zamora",
  "Ceuta",
  "Melilla",
  "La Gomera",
  "Tenerife",
  "Fuerteventura",
  "Ibiza",
  "Menorca",
  "Formentera",
  "Sierra Nevada",
  "Parque Nacional de Doñana",
  "Cabo de Gata",
  "Ronda",
  "Marbella",
  "Torremolinos",
  "Benidorm",
  "Torrevieja",
  "Elche",
  "Alcalá de Henares",
  "San Sebastián de los Reyes",
  "Aranjuez",
  "Getafe",
  "Algeciras",
  "Pontevedra",
  "Tudela",
  "Soria",
  "Teruel",
  "Jerez de la Frontera",
  "Ribeira Sacra",
  "Las Médulas",
  "Cazorla",
  "Cangas de Onís",
  "Covadonga",
  "Llanes",
  "Picos de Europa",
  "Camino de Santiago",
  "Playa de las Catedrales",
  "Montserrat",
  "Siurana",
  "Cadaqués",
  "Figueres",
  "Altea",
  "Peñíscola",
  "Monasterio de Piedra",
  "Valle de Ordesa",
  "Andorra",
  "La Alhambra",
  "Sagrada Familia",
  "Museo del Prado",
  "Casa Batlló",
  "Guggenheim Bilbao",
  "Ciudad de las Artes y las Ciencias",
  "Acueducto de Segovia",
  "Parque Güell",
  "Plaza Mayor de Salamanca",
  "Catedral de Burgos",
  "Catedral de Santiago de Compostela",
];
